### ISSUE TITLE
PayPal IPN Listener as Google Web-App always returns INVALID

### ISSUE THREAD

**Issue by morsagmon** [morsagmon/PayPal-IPN-Listener-Google-Script#1]
The proposed skeleton of a PayPal IPN listener always returns INVALID.

I noticed some discussions on encoding the params string before re-sending to PayPal, but I don't understand why this would be necessary, as I'm re-sending the (supposedly) encoded string as it was sent to me (I'm just adding the required "cmd=_notify-validate" param).

Any help with this will be appreciated :)

**Comment by overint** [comment]
Is there a way to check the encoding of the incoming post request? ie. utf-8 or windows-1252?

**Comment by morsagmon** [comment]
I'm not really sure.
This is what I'm receiving from PayPal, can you tell the encoding used?

`payment_type=instant&payment_date=Tue%20Sep%2027%202016%2018%3A11%3A38%20GMT+0300%20%28Jerusalem%20Daylight%20Time%29&payment_status=Pending&address_status=confirmed&payer_status=verified&first_name=John&last_name=Smith&payer_email=buyer@paypalsandbox.com&payer_id=TESTBUYERID01&address_name=John%20Smith&address_country=United%20States&address_country_code=US&address_zip=95131&address_state=CA&address_city=San%20Jose&address_street=123%20any%20street&business=seller@paypalsandbox.com&receiver_email=seller@paypalsandbox.com&receiver_id=seller@paypalsandbox.com&residence_country=US&item_name=something&item_number=AK-1234&quantity=1&shipping=3.04&tax=2.02&mc_currency=USD&mc_fee=0.44&mc_gross=12.34&mc_gross_1=9.34&txn_type=web_accept&txn_id=248436388&notify_version=2.1&custom=xyz123&invoice=abc1234&test_ipn=1&verify_sign=AFcWxV21C7fd0v3bYYYRCpSSRl31AKRK5.hh-2-88KVU595dZHROiu-x`

**Comment by overint** [comment]
There's a bug with the sandbox, it doesn't send the same encoding parameter as the live endpoints do (which indicates the encoding).

I'm not able to tell from that. can you dump the final string just before you post it back to paypal?

**Comment by morsagmon** [comment]
Yes, this is what I'm posting back:

`https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_notify-validate&payment_type=instant&payment_date=Tue%20Sep%2027%202016%2018%3A11%3A38%20GMT+0300%20%28Jerusalem%20Daylight%20Time%29&payment_status=Pending&address_status=confirmed&payer_status=verified&first_name=John&last_name=Smith&payer_email=buyer@paypalsandbox.com&payer_id=TESTBUYERID01&address_name=John%20Smith&address_country=United%20States&address_country_code=US&address_zip=95131&address_state=CA&address_city=San%20Jose&address_street=123%20any%20street&business=seller@paypalsandbox.com&receiver_email=seller@paypalsandbox.com&receiver_id=seller@paypalsandbox.com&residence_country=US&item_name=something&item_number=AK-1234&quantity=1&shipping=3.04&tax=2.02&mc_currency=USD&mc_fee=0.44&mc_gross=12.34&mc_gross_1=9.34&txn_type=web_accept&txn_id=248436388&notify_version=2.1&custom=xyz123&invoice=abc1234&test_ipn=1&verify_sign=AFcWxV21C7fd0v3bYYYRCpSSRl31AKRK5.hh-2-88KVU595dZHROiu-x`

**Comment by overint** [comment]
You realise it's meant to be a post request?
If so, the URL should definitely not be in there.

**Comment by overint** [comment]
I created a pull #2.
Can you check if that works?

**Comment by morsagmon** [comment]
Yes, you got a point there 👍 
I created a new [pull](https://github.com/morsagmon/PayPal-IPN-Listener-Google-Script/blob/Fixed-IPN-handler-w/-payload-for-post/IPN-listener-payload-post), however, still returns INVALID.

This is the payload I'm sending:

`https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_notify-validate&payment_type=instant&payment_date=Sat%20Oct%2001%202016%2012%3A03%3A17%20GMT+0300%20%28Jerusalem%20Daylight%20Time%29&payment_status=Voided&address_status=confirmed&payer_status=verified&first_name=John&last_name=Smith&payer_email=buyer@paypalsandbox.com&payer_id=TESTBUYERID01&address_name=John%20Smith&address_country=United%20States&address_country_code=US&address_zip=95131&address_state=CA&address_city=San%20Jose&address_street=123%20any%20street&business=seller@paypalsandbox.com&receiver_email=seller@paypalsandbox.com&receiver_id=seller@paypalsandbox.com&residence_country=US&item_name=something&item_number=AK-1234&quantity=1&shipping=3.04&tax=2.02&mc_currency=USD&mc_fee=0.44&mc_gross=12.34&mc_gross_1=9.34&txn_type=web_accept&txn_id=933471269&notify_version=2.1&custom=xyz123&invoice=abc1234&test_ipn=1&verify_sign=AFcWxV21C7fd0v3bYYYRCpSSRl31AfOjf4b0PUhpR.urKDXnuE7Jc5S9`

**Comment by overint** [comment]
You still have the URL in there.
I tagged you, if you merge my pull it shoud work correctly.

**Comment by morsagmon** [comment]
I had to also replace the URL parameter of "fetch".
I updated the master code now - still returns INVALID.

**Comment by morsagmon** [comment]
The issue was the dreaded "+" sign - Java Script implicit encoding did not escape this char - I manually encoded this char and all works. I'll suggest a working skeleton to be added to the sample repo.

**Comment by overint** [comment]
That's the same issue I had when creating the PHP class. I think it would be much easier if they sent the timestamp in a different format. 
Nice to see you got it solved 😄

**Comment by overint** [comment]
Could you update the repo with the new code, and i'll try get the example added into the ipn sample repo.

**Comment by morsagmon** [comment]
Yep. They should encode properly before sending out...
I created a new pull request on the sample repo with my code suggestion to be added...

Thanks!!

**Comment by overint** [comment]
No worries, thanks. We can continue the conversation there :)
